language: python

jdk:
  - openjdk7

python:
  - "2.7"

env:
  global:
    - SPARK_VERSION='1.6.0'
    - HADOOP_VERSION='2.6'
    - SPARK_HOME=/tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION

before_install:
  - pip install -U pip

install:
  - curl http://d3kbcqa49mib13.cloudfront.net/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - tar -xvzf /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry pip install -e . 
 
script: nosetests test

notifications:
  email:
    on_success: always
    on_failure: never

