language: python

jdk:
  - openjdk7

python:
  - "2.7"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - libatlas3gf-base

env:
  global:
    - SPARK_VERSION='1.6.0'
    - HADOOP_VERSION='2.6'
    - SPARK_HOME=/tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION
    - PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
    - PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.9-src.zip:$PYTHONPATH
    - PYTHONPATH=$SPARK_HOME/python/build:$PYTHONPATH

before_install:
  - pip install -U pip

install:
  - curl http://d3kbcqa49mib13.cloudfront.net/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - tar -xvzf /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - pip install -r requirements.txt
 
script: nosetests test

notifications:
  email:
    on_success: always
    on_failure: never

