language: python

jdk:
  - openjdk7

python:
  - "2.7"

env:
  matrix:
    - SPARK_VERSION="1.6.0" PYTHON_VERSION="2.7"

before_install:
  - pip install -U pip

install:
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry pip install -e . 
 
script: nosetests test

