language: python

python:
  - "2.7"
jdk:
  - openjdk7

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - "pip install ."
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"

before_script:
  - export SPARK_VERSION='1.6.0'
  - export HADOOP_VERSION='2.4'
  - export SPARK_HOME=/tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION
  - export PYTHONPATH=$SPARK_HOME/python/:$SPARK_HOME/python/lib/py4j-0.9-src.zip:$PYTHONPATH

  # Download Spark
  - curl http://d3kbcqa49mib13.cloudfront.net/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz	
  - tar -xvzf /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
 
script: 
  - sh run_tests.sh

notifications:
  email:
    on_success: always
    on_failure: never

