language: python

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt

env:
  global:
    - SPARK_VERSION='1.6.0'
    - HADOOP_VERSION='2.6'
    - SPARK_HOME=/tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION
    - PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
    - PYTHONPATH=$SPARK_HOME/python/build:$PYTHONPATH

matrix:
  include:
    - jdk: openjdk7
      python: 2.7
      env: >
        SPARK_VERSION='1.6.0'
        HADOOP_VERSION='2.6'
        SPARK_HOME=/tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION
        PYTHONPATH=$SPARK_HOME/python/:$PYTHONPATH
        PYTHONPATH=$SPARK_HOME/python/build:$PYTHONPATH

before_script:
  # Download Spark
  - curl http://d3kbcqa49mib13.cloudfront.net/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - tar -xvzf /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
 
script: nosetests test

notifications:
  email:
    on_success: always
    on_failure: never

